In [12]:
import pandas as pd

In [13]:
from matplotlib import pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

In [9]:
import numpy as np

In [ ]:
x=[1,2,3]
y=[2,3,6]
plt.plot(x,y)
plt.xlabel("x")
plt.ylabel("y")
plt.title("linear")
plt.show()


In [11]:
sample_data=pd.read_csv('sample_data.csv')

In [14]:
sample_data

NameError: name 'sample_data' is not defined

In [10]:
sample_data.column_b

NameError: name 'sample_data' is not defined

In [16]:
sample_data.column_c

0    10
1     8
2     6
3     4
4     2
Name: column_c, dtype: int64

In [19]:
data=pd.read_csv('countries.csv')

In [20]:
data

country  year  population
0     Afghanistan  1952     8425333
1     Afghanistan  1957     9240934
2     Afghanistan  1962    10267083
3     Afghanistan  1967    11537966
4     Afghanistan  1972    13079460
...           ...   ...         ...
1699     Zimbabwe  1987     9216418
1700     Zimbabwe  1992    10704340
1701     Zimbabwe  1997    11404948
1702     Zimbabwe  2002    11926563
1703     Zimbabwe  2007    12311143

[1704 rows x 3 columns]

In [21]:
a=np.array([[1,2,3], [1,2,3]])
print(a)


[[1 2 3]
 [1 2 3]]


In [5]:
!pip install numpy

In [22]:
np.shape(a)

(2, 3)

np.size(a)

In [23]:
np.size(1,2)

IndexError: tuple index out of range

In [15]:
print('hello')

hello


In [7]:
a=[2,3,1,5,0]
a.sort()
print(a[2])

2


In [8]:
cars = ['Ford', 'BMW', 'Volvo']

cars.sort()
print(cars)

['BMW', 'Ford', 'Volvo']


In [25]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [30]:
np.random.rand(4,4)

array([[0.57121442, 0.19304101, 0.72040298, 0.518287  ],
       [0.60489109, 0.47239597, 0.40821121, 0.81249433],
       [0.59209668, 0.08954742, 0.35219156, 0.80313489],
       [0.47648202, 0.02424112, 0.38058097, 0.80890385]])

In [52]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3, axis=0)
r2=np.repeat(arr,3, axis=0)
r=r1*r2
print(r)


[[1 4 9]
 [1 4 9]
 [1 4 9]]


In [3]:
z=np.random.randint(4,7, size=(4,4))
print(z)
z[1:-1,0:4]

[[5 6 6 5]
 [5 5 5 5]
 [6 6 5 5]
 [4 6 6 5]]


array([[5, 5, 5, 5],
       [6, 6, 5, 5]])

In [20]:
np.ones((3,3))
np.zeros((5,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
for i in range (0,5):
    print("*"*(i*i))


*
****
*********
****************


In [18]:
num=int(input('any number'))
if (num % 2) == 0:

              print ('The number is even')

else:
           print ('The provided number is odd')



any number45
The provided number is odd
